version: "3"

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PASSWORD=abc123
      - API_HOST=api
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - TEST=0
    volumes:
      - ./src:/src
      - ./tests:/tests
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
      - --port=80
    ports:
      - "5005:80"

  postgres:
    image: postgres:10-alpine
    environment:
      - POSTGRES_USER=accounting
      - POSTGRES_PASSWORD=abc123
    ports:
      - "54321:5432"
